### ISSUE TITLE
cookie authentication results in HTTP 401

### ISSUE THREAD

**Issue by plebhash** [rust-bitcoin/rust-bitcoincore-rpc#316]
I need to use a cookie file for authentication.

Doing this via `bitcoin-cli` works just fine:
```shell
$ bitcoin-cli -rpcport=38332 -rpccookiefile="/path/to/.cookie" getblockchaininfo
{
  "chain": "signet",
  "blocks": 552784,
  "headers": 552784,
  "bestblockhash": "00000096cdd866485a3edae510ec320e7d4070eaaf23fa21b283cc1b4bafad75",
  "difficulty": 0.001126515290698186,
  "time": 1699119490,
  "mediantime": 1699119336,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000000000000000026ebaf0c654",
  "size_on_disk": 324185080,
  "pruned": false,
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}
```

---

But using `bitcoincore-rpc v0.17.0` is not working as expected.

`Cargo.toml`:
```toml
[dependencies]
bitcoincore-rpc = { version = "0.17.0" }
```

`main.rs`:
```rust
use bitcoincore_rpc::RpcApi;

fn main() {
    let rpc_url = "0.0.0.0:38332";
    let rpc = bitcoincore_rpc::Client::new(
        &rpc_url,
        bitcoincore_rpc::Auth::CookieFile("/path/to/.cookie".into()),
    ).unwrap();

    let res = rpc.get_blockchain_info().unwrap();

    println!("{:?}", res);
}
```

error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JsonRpc(Transport(HttpErrorCode(401)))', src/main.rs:10:41
stack backtrace:
   0: begin_panic_handler
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:593:5
   1: panic_fmt
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panicking.rs:67:14
   2: unwrap_failed
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/result.rs:1076:23
   4: tmp::main
             at ./src/main.rs:10:15
   5: core::ops::function::FnOnce::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

**Comment by plebhash** [comment]
my `bitcoind` version is `v24.99.0`, and given the [`Supported Bitcoin Core Versions`](https://github.com/rust-bitcoin/rust-bitcoincore-rpc#supported-bitcoin-core-versions) this could be related to versioning

**Comment by plebhash** [comment]
the root cause of this issue was the fact that I was doing a `cat` on the original `.bitcoin/.cookie` file, and then copy/pasting the contents into a new file to be consumed by my `rust-bitcoincore-rpc` code.
